[tool.poetry]
name = "tema"
version = "0.1.0"
description = ""
authors = ["Darius"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort = "^4.3.21"
pylint = "^2.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
